#!/bin/bash
#kusime kasutajast tema vanust
echo -n "Sisestage praegune kuu number:  "
read kuu

#Kontrollime kas uldse see on number voi mitte
if ! [[ "$kuu" =~ ^[0-9]+$ ]]; then
    echo "Vigane sisend! Sisestage arvuline vanus."
    exit 1
fi

#ja nuud leiame
if [ "$kuu" == "1" ]; then
        echo "Praegu on Jaanuari"
        echo "Praegu on Talv"
elif [ "$kuu" == "2" ]; then
        echo "Praegu on Veebruari"
        echo "Praegu on Talv"
elif [ "$kuu" == "3" ]; then
        echo "Praegu on Märts"
        echo "Praegu on Kevad"
elif [ "$kuu" == "4" ]; then
        echo "Praegu on Aprill"
        echo "Praegu on Kevad"
elif [ "$kuu" == "5" ]; then
        echo "Praegu on Mai"
        echo "Praegu on Kevad"
elif [ "$kuu" == "6" ]; then
        echo "Praegu on Juuni"
        echo "Praegu on Suvi"
elif [ "$kuu" == "7" ]; then
        echo "Praegu on Juuli"
        echo "Praegu on Suvi"
elif [ "$kuu" == "8" ]; then
        echo "Praegu on August"
        echo "Praegu on Suvi"
elif [ "$kuu" == "9" ]; then
        echo "Praegu on September"
        echo "Praegu on Sugis"
elif [ "$kuu" == "10" ]; then
        echo "Praegu on Oktoober"
        echo "Praegu on Sugis"
elif [ "$kuu" == "11" ]; then
        echo "Praegu on November"
        echo "Praegu on Sugis"
elif [ "$kuu" == "12" ]; then
        echo "Praegu on Detsember"
        echo "Praegu on Talv"
else
        echo "See kuu ei eksisteeri"
fi
